"""rename address

Revision ID: 7c6f079ce421
Revises: 72b9960d7b9f
Create Date: 2025-06-17 22:48:39.037949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6f079ce421'
down_revision = '72b9960d7b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
